version: "3.9"

services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./inits/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
    networks:
      - mynetwork

  nats-streaming:
    image: nats-streaming:0.25.6-alpine
    ports:
      - "4222:4222"
      #- "8222:8222"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres: